### ISSUE TITLE
fail to open jar when i execute command "blade c jvm script ……"

### ISSUE THREAD

**Issue by chjh0612** [chaosblade-io/chaosblade#386]
**please help!! thanks a lot**

I execute the command "blade c jvm script ……". it return success.
but it throw exception when compile the script.

###  _Fail to open jar:file:alipay-sdk-java-1.0.jar!/ as a jar file_

The exception detail is shown below。
ps: I delete some sensitive information

`Match rule: {"action":{"name":"script"},"actionName":"script","matcher":{"matchers":{"classname":"com........},"target":"jvm"}
2020-06-28 10:13:18 WARN  inject exception
java.lang.RuntimeException: java.lang.RuntimeException: Fail to open jar:file:/.........../deploy/projectname/lib/alipay-sdk-java-1.0.jar!/ as a jar file
        at com.sun.tools.javac.main.Main.compile(Main.java:559)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine.compileClass(JavaCodeScriptEngine.java:148)
        at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine.compile(JavaCodeScriptEngine.java:112)
        at com.alibaba.chaosblade.exec.plugin.jvm.script.base.AbstractScriptEngineService.doCompile(AbstractScriptEngineService.java:82)
        at com.alibaba.chaosblade.exec.plugin.jvm.script.base.AbstractScriptEngineService.compile(AbstractScriptEngineService.java:69)
        at com.alibaba.chaosblade.exec.plugin.jvm.script.model.DynamicScriptExecutor.run(DynamicScriptExecutor.java:72)
        at com.alibaba.chaosblade.exec.common.injection.Injector.inject(Injector.java:71)
        at com.alibaba.chaosblade.exec.common.aop.BeforeEnhancer.beforeAdvice(BeforeEnhancer.java:51)
        at com.alibaba.chaosblade.exec.common.plugin.MethodEnhancer.beforeAdvice(MethodEnhancer.java:41)
        at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.BeforeEventListener.handleEvent(BeforeEventListener.java:76)
        at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.BeforeEventListener.onEvent(BeforeEventListener.java:49)
        at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleEvent(EventListenerHandler.java:116)
        at com.alibaba.jvm.sandbox.core.enhance.weaver.EventListenerHandler.handleOnBefore(EventListenerHandler.java:350)
        at java.com.alibaba.jvm.sandbox.spy.Spy.spyMethodOnBefore(Spy.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
        at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Fail to open jar:file:/opt/scf/service/deploy/projectname/lib/alipay-sdk-java-1.0.jar!/ as a jar file
        at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine$InMemoryJavaFileManager.processJar(JavaCodeScriptEngine.java:424)
        at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine$InMemoryJavaFileManager.listUnder(JavaCodeScriptEngine.java:395)
at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine$InMemoryJavaFileManager.find(JavaCodeScriptEngine.java:384)       at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine$InMemoryJavaFileManager.list(JavaCodeScriptEngine.java:369)       at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:231)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2796)
        at com.sun.tools.javac.comp.Resolve.findType(Resolve.java:2069)
        at com.sun.tools.javac.comp.Resolve.findIdent(Resolve.java:2098)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitIdentifier(Attr.java:387)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitIdentifier(Attr.java:369)
        at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2017)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:372)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:369)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:53)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:372)
        at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:369)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1903)
        at com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:365)
        at com.sun.tools.javac.main.JavaCompiler.resolveIdent(JavaCompiler.java:705)
        at com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:125)
        at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:108)
        at com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:61)
        at org.springframework.boot.configurationprocessor.TypeUtils.getDeclaredType(TypeUtils.java:86)
        at org.springframework.boot.configurationprocessor.TypeUtils.<init>(TypeUtils.java:75)
        at org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.init(ConfigurationMetadataAnnotationProcessor.java:109)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
 at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 31 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaCodeScriptEngine$InMemoryJavaFileManager.processJar(JavaCodeScriptEngine.java:408)
        ... 71 common frames omitted
`

**Comment by tiny-x** [comment]
Can you provide the script content
