### ISSUE TITLE
blade prepare jvm -p tomcat

### ISSUE THREAD

**Issue by pchandrasekhar210893** [chaosblade-io/chaosblade#481]
## Issue Description
Logs 
{"code":604,"success":false,"error":"java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.LinuxAttachProvider not found\n\tat java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)\n\tat java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)\n\tat java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)\n\tat java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)\n\tat jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:258)\n\tat jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.\u003cinit\u003e(CoreLauncher.java:20)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)\ncom.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:165)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.\u003cinit\u003e(CoreLauncher.java:20)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)\nsandbox load jvm failed : Agent JAR loaded but agent failed to initialize\n exit status 255","result":"604f0b847fe32f84"}

### How to reproduce it (as minimally and precisely as possible)

1. Run a tomcat application on linux instance and use blade 0.10.0 version. 
2. Command to run "blade prepare jvm -p tomcat"
3.

**Comment by pchandrasekhar210893** [comment]
Can you please update on this !!

**Comment by xcaspar** [comment]
@pchandrasekhar210893 Please provide the JDK version.

**Comment by pchandrasekhar210893** [comment]
Thank you for considering the issue. The JDK version is openjdk version "11.0.10" 2021-01-19

**Comment by idiot40** [comment]
solved?

**Comment by xcaspar** [comment]
If you find the above problems, you can view logs/sandbox/sandbox.log in the user directory of the application process. For example, if the user is admin, the log path is /home/admin/logs/sandbox/sandbox.log. cc @idiot40

**Comment by angjuLin** [comment]
@xcaspar 这个问题有解决么，我也是jdk11，执行命令下发的时候，出现这个错误，logs/sandbox/sandbox.log 里没有什么异常信息

**Comment by LY1806620741** [comment]
一样的问题在https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u462-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u462b08.tar.gz

chaosblade 1.8.0

**Comment by xcaspar** [comment]
> 一样的问题在https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u462-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u462b08.tar.gz
> 
> chaosblade 1.8.0

需要查看下应用进程用户目录下 logs/sandbox/sandbox.log 日志

**Comment by LY1806620741** [comment]
> > 一样的问题在https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u462-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u462b08.tar.gz
> > chaosblade 1.8.0
> 
> 需要查看下应用进程用户目录下 logs/sandbox/sandbox.log 日志

```bash
./blade prepare jvm --javaHome /usr/lib/jvm/temurin-8-jdk --pid 7 
{"code":63063,"success":false,"error":"`/bin/sh -c  /usr/lib/jvm/temurin-8-jdk/bin/java -Xms128M -Xmx128M -Xnoclassgc -ea -Xbootclasspath/a:/usr/lib/jvm/temurin-8-jdk/lib/tools.jar -jar /tmp/chaosblade-1.8.0-linux_amd64/lib/sandbox/lib/sandbox-core.jar 7 \"/tmp/chaosblade-1.8.0-linux_amd64/lib/sandbox/lib/sandbox-agent.jar\" \"home=/tmp/chaosblade-1.8.0-linux_amd64/lib/sandbox;token=152199343929;server.ip=127.0.0.1;server.port=42237;namespace=chaosblade\"`: cmd exec failed, err: Picked up JAVA_TOOL_OPTIONS: \ncom.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize\n\tat sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.\u003cinit\u003e(CoreLauncher.java:20)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)\nsandbox load jvm failed : Agent JAR loaded but agent failed to initialize\n exit status 255","result":"1801980a4b4a7a34"}
```
只有这些信息,没有logs/sandbox/sandbox.log日志


另外sa我看sanbox比较老旧了,试图直接使用sanbox1.4.0也是一样的错误
```shell
bash-5.2$ HOME=$(pwd);./sandbox.sh -p 7
ls: cannot access '(path': No such file or directory
Picked up JAVA_TOOL_OPTIONS: 
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:61)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.<init>(CoreLauncher.java:20)
        at com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)
sandbox load jvm failed : Agent JAR loaded but agent failed to initialize
attach JVM 7 fail.
```

另外,这个pid,arthas可以attach成功

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/question` | Status: **Answered**

`blade prepare jvm -p tomcat` fails with `Agent JAR loaded but agent failed to initialize` and `ServiceConfigurationError: LinuxAttachProvider not found`.

**Root Cause (from @xcaspar):** The error `Provider sun.tools.attach.spi.AttachProvider not found` indicates that the JDK's `tools.jar` is not in the classpath. This typically happens when:
1. Using JRE instead of JDK
2. `JAVA_HOME` points to the wrong location
3. JDK version mismatch between the blade tool and the target JVM

**Status:** The user is using OpenJDK 11 (as shown in the error stack trace). ChaosBlade v1.0.x had limited JDK 11 support.

**Solution:**
1. **Upgrade ChaosBlade** to v1.7.x+ which has better JDK 11+ support
2. **Specify javaHome explicitly:**
   ```bash
   blade prepare jvm -p tomcat --javaHome /usr/lib/jvm/java-11-openjdk
   ```
3. **Ensure tools.jar is accessible:**
   ```bash
   ls /usr/lib/jvm/java-11-openjdk/lib/tools.jar
   # For JDK 11+, tools.jar is replaced by jdk.attach module
   ```
4. **Add JVM flags for JDK 11+:**
   ```bash
   # In Tomcat's setenv.sh
   export JAVA_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"
   ```

**Related:** #664 (JVM prepare error 63063), #735 (two Java processes), #602 (JDK16 error)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
