### ISSUE TITLE
docker file chmod scene failed because

### ISSUE THREAD

**Issue by hengyoush** [chaosblade-io/chaosblade#884]
## Issue Description
*bug report*  
容器执行file-chmod场景时失败
Type: *bug report* , *feature request* or *question*

### Describe what you expected to happen
日志提示：
```
time="2023-04-23 11:32:58.977946834 UTC" level=debug msg="Command Result, output: panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8a5e7a]\n\ngoroutine 1 [running]:\ngithub.com/chaosblade-io/chaosblade-exec-os/exec/file.(*FileChmodActionExecutor).Exec(0xc0000e73c0, 0x7ffc5db3dbbe, 0x10, 0xab7820, 0xc0001b4180, 0xc0001948c0, 0xab7820)\n\t/chaosblade-exec-os/exec/file/file_chmod.go:120 +0x3ca\nmain.main()\n\t/chaosblade-exec-os/main.go:150 +0x6c6\n, err: exit status 2" location="/go/pkg/mod/github.com/chaosblade-io/chaosblade-exec-cri@v1.7.0/exec/executor_common_linux.go:113" uid=ce7f725a34bea975
```
经过排查，发现是如下代码导致：
```go
fileInfo, _ := os.Stat(filepath)
```
这是直接在宿主机上执行的，是不到容器内的文件的
结果修复，改为：
```go
response = f.channel.Run(ctx, "stat", fmt.Sprintf(`-c "%%a" %s`, filepath))
```
通过nsexec的channel执行stat -c %a命令获取权限码

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by hengyoush** [comment]
i can fix this issue

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Confirmed** | Severity: **Medium** | `good first issue`

`blade create docker file chmod` causes a panic: `runtime error: invalid memory address or nil pointer dereference` at `file_chmod.go:120`.

**Root Cause (identified by @hengyoush):** The code calls `os.Stat(filepath)` without checking for errors:
```go
fileInfo, _ := os.Stat(filepath)  // _ ignores the error!
// Later:
fileInfo.Mode()  // nil pointer dereference if file doesn't exist
```

When the file doesn't exist or is inaccessible inside the container, `os.Stat` returns `nil` and an error. The error is ignored (`_`), and the subsequent `fileInfo.Mode()` call panics.

**Fix:**
```go
fileInfo, err := os.Stat(filepath)
if err != nil {
    return spec.ResponseFailWithResult(spec.FileNotExist, ...)
}
```

**Affected Component:** `chaosblade-exec-os` file chmod implementation

**Status:** @hengyoush volunteered to fix this issue.

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
