### ISSUE TITLE
chaosblade-exec-jvm jackson-core version need bump to 2.12.7

### ISSUE THREAD

**Issue by hengyoush** [chaosblade-io/chaosblade#891]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
chaosblade-exec-jvm version:  master
when i use the newest branch to create jvm experiment, it failed with the following message: 
```
2023-05-13 01:12:08 default WARN  path=/chaosblade/create invoke module chaosblade method create occur error.
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:656)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.SandboxModule.getRequestFromBody(SandboxModule.java:195)
	at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.SandboxModule.service(SandboxModule.java:149)
	at com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.SandboxModule.create(SandboxModule.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doMethod(ModuleHttpServlet.java:133)
	at com.alibaba.jvm.sandbox.core.server.jetty.servlet.ModuleHttpServlet.doPost(ModuleHttpServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:351)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:900)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:954)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:748)
```
This may be due to a mismatch between the jackson-core version and the jackson-databind version
```xml
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.7.1</version>
        </dependency>
```
i update jackson-core version to 2.12.7, the problem seems to be solved

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/enhancement` | Status: **Confirmed** | Severity: **Medium**

`chaosblade-exec-jvm` fails with `java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature` because the bundled `jackson-core` version is too old.

**Root Cause:** The `jackson-databind` dependency requires a newer `jackson-core` that includes `JacksonFeature`, but the version pinned in `chaosblade-exec-jvm` is too old.

**Fix:** Bump `jackson-core` to at least v2.12.7 in the `pom.xml`:
```xml
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.12.7</version>
</dependency>
```

**Affected Component:** `chaosblade-exec-jvm` Maven dependencies

**Note:** This should also include bumping `jackson-databind` and `jackson-annotations` to matching versions to avoid version conflicts. Consider using the Jackson BOM for consistent versioning:
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson</groupId>
            <artifactId>jackson-bom</artifactId>
            <version>2.12.7</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
